version: '3.8'

services:
  backend:
    build: ./backend
    container_name: italian-brainrot-backend
    volumes:
      # Mount for persistent video storage
      - ./backend/static:/app/static
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: italian-brainrot-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
